[package]
name = "bevy-runeweave-runtime-cdylib"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "bevy_runeweave"
crate-type = ["cdylib"]

[features]
default = []
documentation = ["bevy-runeweave/documentation"]
dynamic_components = ["bevy-runeweave/dynamic_components"]
script_systems = ["bevy-runeweave/script_systems"]
full_scripting = ["documentation", "dynamic_components", "script_systems"]

[dependencies]
bevy-runeweave = { path = "../..", default-features = false, features = ["unified"] }

[target.'cfg(target_os = "android")'.dependencies]
bevy = { version = "0.19.1", default-features = false, features = ["android-native-activity"] }
jni = "0.22.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
