[package]
name = "bevy_mod_scripting"
description = "Multi language scripting in Bevy"
include = ["readme.md", "/src", "LICENSE-MIT"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lib]
name = "bevy_mod_scripting"
path = "src/lib.rs"
bench = false

[package.metadata."docs.rs"]
features = ["lua55", "quickjs"]

[features]
default = []
lua = ["bevy_mod_scripting_lua"]
lua55 = ["bevy_mod_scripting_lua/lua55", "lua"]
quickjs = ["bevy_mod_scripting_quickjs"]
typescript = ["quickjs"]

[dependencies]
bevy_app = { workspace = true }
bevy_mod_scripting_core = { workspace = true }
bevy_mod_scripting_lua = { workspace = true, optional = true }
bevy_mod_scripting_quickjs = { workspace = true, optional = true }
bevy_mod_scripting_asset = { workspace = true }
bevy_mod_scripting_bindings = { workspace = true }
bevy_mod_scripting_script = { workspace = true }
