[package]
name = "bevy_mod_scripting_quickjs"
description = "QuickJS support for bevy_mod_scripting"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lib]
name = "bevy_mod_scripting_quickjs"
path = "src/lib.rs"

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_log = { workspace = true }
bevy_mod_scripting_asset = { workspace = true }
bevy_mod_scripting_bindings = { workspace = true }
bevy_mod_scripting_core = { workspace = true }
bevy_mod_scripting_script = { workspace = true }
bevy_platform = { workspace = true }
rquickjs = { workspace = true, features = ["parallel"] }

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
rquickjs = { workspace = true, features = ["bindgen", "parallel"] }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["bevy_platform"]
