[package]
name = "bevy-runeweave-runtime-staticlib"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "bevy_runeweave"
crate-type = ["staticlib"]

[features]
default = []
documentation = ["bevy-runeweave/documentation"]
dynamic_components = ["bevy-runeweave/dynamic_components"]
script_systems = ["bevy-runeweave/script_systems"]
full_scripting = ["documentation", "dynamic_components", "script_systems"]

[dependencies]
bevy-runeweave = { path = "../..", default-features = false, features = ["unified"] }
