[package]
name = "bevy-runeweave-runtime-staticlib"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "bevy_runeweave"
crate-type = ["staticlib"]

[features]
default = ["unified"]
unified = ["bevy-runeweave/unified"]
js = ["bevy-runeweave/js"]
typescript = ["bevy-runeweave/typescript"]
lua = ["bevy-runeweave/lua"]

[dependencies]
bevy-runeweave = { path = "../..", default-features = false }
