[package]
name = "bevy_mod_scripting_lua"
description = "Necessary functionality for Lua support with bevy_mod_scripting"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[package.metadata."docs.rs"]
features = ["lua55"]

[package.metadata.release]
enable-features = ["lua55"]

[features]
lua55 = ["dep:mlua", "mlua/lua55"]
luau = ["dep:mlua", "mlua/luau"]

[lib]
name = "bevy_mod_scripting_lua"
path = "src/lib.rs"

[dependencies]
bevy_app = { workspace = true, default-features = false, features = [] }
bevy_ecs = { workspace = true, default-features = false, features = [] }
bevy_log = { workspace = true, default-features = false, features = [] }
bevy_platform = { workspace = true, default-features = false, features = [] }
bevy_mod_scripting_core = { workspace = true }
bevy_mod_scripting_bindings = { workspace = true }
bevy_mod_scripting_asset = { workspace = true }
bevy_mod_scripting_script = { workspace = true }
mlua = { workspace = true, optional = true, features = ["vendored", "send"] }

[dev-dependencies]
bevy_asset = { workspace = true, default-features = false }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["bevy_platform"]
