[package]
name = "script-squadron-luau"
version = "0.1.0"
edition = "2024"
authors.workspace = true
build = "../../scripts/embed-windows-icon.rs"

[dependencies]
bevy-runeweave = { path = "../..", default-features = false, features = ["luau"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
